version: "3.8"

services:
  frontend:
    image: mahmoudarsela/advocateai-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3000/api/v1

  backend:
    image: mahmoudarsela/backend-addvocate:latest
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://dev:dev@localhost:5432/tech_test?schema=public
      PORT: "3000"
      JWT_SECRET: acJDwt&51+frfcsvJ
      JWT_EXPIRATION: "1d"
      OPENAI_API_KEY: "put your key here"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tech_test
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
